### ISSUE TITLE
return a jQuery promise from retrieveJSON

### ISSUE THREAD

**Issue by krisselden** [wycats/jquery-offline#5]

**Comment by stilist** [comment]
+1

Was hoping to have drop-in optional caching, e.g.

``` coffeescript
xhr = if settings.cache then $.retrieveJSON(url) else $.getJSON(url)
xhr.done(settings.done).fail(settings.fail).always(settings.always)
```

But when the `$.retrieveJSON` path is hit I just get `Uncaught TypeError: Cannot read property 'jquery' of undefined`.

**Comment by craigspaeth** [comment]
+1

**Comment by stilist** [comment]
Is this resolved by https://github.com/wycats/jquery-offline/commit/b2139ff18cb74a2cad252f51040af07cbc512d9d?

**Comment by krisselden** [comment]
Still doesn't look like the above example would work.  That commit still requires a callback function.  It also returns a promise that will never resolve, if you return false from your callback function if it is cached.
